### ISSUE TITLE
build123d to blender

### ISSUE THREAD

**Issue by rsaccon** [uki-dev/blendquery#1]
I was thinking about a way to use Blender to 3d-draw build123d scripts (so I can use Lapce as editor, because VScode is too bloated for my taste) and I found this great project. I tried to understand what your scripts are doing. At the master branch, all made sense to me. However the new-generation branch, where everything is supposed to be improved, I could not really understand where you execute the cadquery script and process its output. Is it because it is still WIP or does it work completely different than at the master branch ? In case you are familiar with build123d, you have any thoughts on wether there are any significant differences for implementing a bridge to blender as in cadquery ?

**Comment by 42sol-eu** [comment]
Nice to read this.
I was also looking into BlendQuery and possible ways to add build123d.

The part that is missing in build123d is the specific exporter 'GLTF' this would be needed to be investigated.

Maybe one way would be to mix CadQuery and build123d.

Felix 

My notes:

in CadQuery
  Assembly.exportGLTF()
  calling OCP.RWGltf.RWGltf_CafWriter
  from OCP-stubs which is a requirement for build123d

**Comment by 42sol-eu** [comment]
Hi @rsaccon and @uki-dev are you active on the CadQuery Discord Server? It might be intrto have a more direct way of communication 
Felix

**Comment by rsaccon** [comment]
yes I am there (but not yet very active)

**Comment by rsaccon** [comment]
Just accidentally stumbled upon this: https://github.com/bernhard-42/ocp-tessellate

So maybe it is more performant and more flexible (but for sure way more work involved to get it done), just to tesselate and generate all the 3d-objects in blender, instead of exporting from build123d and importing in blender

**Comment by uki-dev** [comment]
Sorry, I have been on holiday 🌴 

> However the new-generation branch, where everything is supposed to be improved, I could not really understand where you execute the cadquery script and process its output. Is it because it is still WIP or does it work completely different than at the master branch ?

https://github.com/uki-dev/blendquery/commit/e9003a435b2256352ebd088129c2e04881b2cebe should be stable but it does not support build123d yet. Additionally, the interop between script and Blender has changed. BlendQuery now evaluates all global variables defined by a script. If they are a valid topology object and they are not prefixed by `_` (used to hide objects), it generates them into the scene. 
The branch requires some additional clean up and changes to fully support build123d, but having discussed this with the primary maintainer of build123d, it should be pretty trivial.


> Just accidentally stumbled upon this: https://github.com/bernhard-42/ocp-tessellate
> 
> So maybe it is more performant and more flexible (but for sure way more work involved to get it done), just to tesselate and generate all the 3d-objects in blender, instead of exporting from build123d and importing in blender

The new generation is using the `Shape.tessellate` method which is doing something very similar to `ocp-tessellate` and is very performant. I will definitely consider `ocp-tessellate` should I run into any complications, but I would like to avoid the added complexity for now, as both libraries already expose this `tessellate` method.

I very much appreciate the interest you have both shown in the project, and I will do my best to progress its development with the time that I have available. I will keep you both posted for when I finish adding build123d and merge my changes into `main` with sufficient documentation in place.

I am relatively active on the CadQuery Discord under the username `uki.dev`, if you would like to have a chat.

**Comment by uki-dev** [comment]
> Could you try e9003a4? It should be usable as before.

Forgive me, this not entirely inaccurate. The interop between CadQuery script and Blender has changed and I have not yet documented this. BlendQuery now evaluates all variables defined by a CadQuery script, and if their name is not prefixed by `_`, renders them into the Blender scene.

**Comment by rsaccon** [comment]
thanks for the detailed reply, now everything makes sense ...

**Comment by 42sol-eu** [comment]
great I am interested to help and support you (as mentioned on Discord)
Felix

**Comment by uki-dev** [comment]
Build123d support has been merged into `main`. Please let me know if you run into any issues.
