### ISSUE TITLE
How to import or create a file?

### ISSUE THREAD

**Issue by mukral** [uki-dev/blendquery#2]
Hi,

installtion of addon is fine, everything is displayed and on place like in description and then?
I copied&pasted the path of a build123d-file but nothing happened. Also I couldn't open an editor to create a new file.
Would you please provide a short "Hello, world"?

Thank you very much
Markus

**Comment by mukral** [comment]
ok, understood - went to scripting and pasted a short b3d-script that I could select in the drop down menue. But after that also nothing happend...

**Comment by uki-dev** [comment]
Hi @mukral, sorry for not getting back to you sooner. Could you please view the `example.blend` file and see if this works for you? It has an example of using Build123d with the only difference is that the text being internal to the `.blend` file itself. All you will need to do is point the text object in blender to the file you have on disk.

**Comment by mukral** [comment]
Hi, I could open the example.blend and the bottle was shown.
Then I've copied own code into the editor and got an error 
"no module named OCP"
but I think this is another topic...

Markus

**Comment by uki-dev** [comment]
After https://github.com/uki-dev/blendquery/issues/5 is resolved please let me know if you are still having troubles importing scripts.

**Comment by mukral** [comment]
works now - thanks!
