### ISSUE TITLE
Addon does not work any after update to Blender 4.1

### ISSUE THREAD

**Issue by mukral** [uki-dev/blendquery#5]
Hi, I could install blendquery in Blender 4.0 but it didn't open after update to 4.1.

So I've tried to reinstall blendquery again and received the error message

line 5, in <module>
from OCP.gp import{
 "ModuleNotFoundError: No module named 'OCP'

build123d and cadquery runs fine with vs code and also "pip show OCP" outputs "version 0.1.9" so I think OCP is installed...

Did I miss something?

Thank you
Markus

**Comment by uki-dev** [comment]
I have not yet tested on 4.1. I will do so and get back to you.
Are you running `pip show OCP` within Blender's Python environment or another Python environment on your system?

**Comment by uki-dev** [comment]
I am able to reproduce this in 4.1. Looking into a fix now 👍

**Comment by uki-dev** [comment]
I've pushed two commits that should both resolve this specific issue directly, as well as improve the overall experience when encountering install/import errors:
- https://github.com/uki-dev/blendquery/commit/8dbd6bb011c65f0a5d8951562fb7555e20429649
- https://github.com/uki-dev/blendquery/commit/13a587b16e5688e3b824444866908fa9ecd25c35

@mukral could you please pull these commits from main, delete the `blendquery` folder found in your `~` or `%USERPROFILE%` directory, and then test whether this resolves things on your end when you try to re-enable the addon and install dependencies?

**Comment by mukral** [comment]
yes, works now - thanks!
